### ISSUE TITLE
Documentation regarding setting is unclear

### ISSUE THREAD

**Issue by slertt** [BigBurritoInc/myBitbucket#63]
What are the settings If URL of pull request is 
https://bitbucket.org/BigBurritoInc/BitbucketHelper4Idea/pull-requests/11948/ticket-name/diff 

What are then the settings 
Project: BigBurritoInc
Repository: BitbucketHelper4Idea
Bitbucket URL: https://bitbucket.org/BigBurritoInc/BitbucketHelper4Idea/
Login: user@email.com

**Comment by palyuga** [comment]
@slertt, is it a question or do you suggest to write it in the way you provided?

**Comment by slertt** [comment]
Both basically.

**Comment by lazb** [comment]
@palyuga I'm using same approach as @slertt  and I get this:

Request failed

```
java.lang.RuntimeException: Status code: 404, reason Not Found
	at http.HttpResponseHandler$Companion.process(HttpResponseHandler.kt:46)
	at http.HttpResponseHandler$Companion.access$process(HttpResponseHandler.kt:19)
	at http.HttpResponseHandler.handle(HttpResponseHandler.kt:17)
	at bitbucket.BitbucketClient.sendRequest(BitbucketClient.kt:135)
	at bitbucket.BitbucketClient.replayPageRequest(BitbucketClient.kt:139)
	at bitbucket.BitbucketClient.inbox(BitbucketClient.kt:85)
	at bitbucket.BitbucketClient.inbox$default(BitbucketClient.kt:79)
	at bitbucket.BitbucketClient.reviewedPRs(BitbucketClient.kt:40)
	at UpdateTaskHolder$UpdateTask.run(UpdateTaskHolder.kt:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by palyuga** [comment]
@lazb, well, the plugin now works only with Bitbucket Server (formerly known as Stash).
In case you use Bitbucket Server, "Bitbucket URL" parameter should contain only the base url of your bitbucket, e.g. `https://yourbbaddress.com`

**Comment by schrizsz** [comment]
Do you plan to make it work for bitbucket cloud?

**Comment by palyuga** [comment]
There is a ticket about that: https://github.com/BigBurritoInc/BitbucketHelper4Idea/issues/69
Though it is pretty big effort, so any help is appreciated

**Comment by palyuga** [comment]
Bitbucket Cloud support was added in the latest plugin version
